### ISSUE TITLE
MessageCache

### ISSUE THREAD

**Issue by MJHC** [Diesel-Jeans/signal#45]

**Comment by alexsteffensen** [comment]
We will use Redis for this and make the server **stateless**

**Comment by alexsteffensen** [comment]
- [ ] Lave insert method - alex
- [ ] Lave remove method - alex
- [ ] Lave hasMessages method - Andreas
- [ ] Lave getAllMessages
- [ ] Lave getNextMessagePage
- [ ] Lave getMessagesToPersist
- [ ] Lave clear method
