### ISSUE TITLE
Client Presence

### ISSUE THREAD

**Issue by MJHC** [Diesel-Jeans/signal#61]
When a client connects with websocket the client must be tracked in a presence manager of some sort, and when the client disconnects they must be removed.

This can be implemented as a manager with redis or a simple inmem hashmap. refer to `ClientPresenceManager.java` in the signal-server repo.

The handling should be done in the `SocketManager.handle_socket` on the server.

**Comment by alexsteffensen** [comment]
- [ ] Setup data structure
- [ ] Add DisplacedPresenceListener to WebsocketConnection
- [ ] Implement set_present()
- [ ] Implement renew_presence()
- [ ] Implement clear_presence()
- [ ] Implement disconnect_all_presences(), disconnect_all_presences_for_uuid() and disconnect_presence()
